version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    env_file: .env.docker
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    restart: always
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: